[book]
authors = ["Dimitri Kokkonis <dimitri.kokkonis@cea.fr>"]
language = "en"
multilingual = false
src = "src"
title = "CS artifact template"

[output.html]
git-repository-url = "https://github.com/kokkonisd/cs-artifact-template"
