name: Publish doc to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install mdBook
        run: rustup update stable && rustup default stable && cargo install mdbook
      - name: Build doc
        run: mdbook build ./doc
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload doc
        uses: actions/upload-pages-artifact@v3
        with:
          path: "doc/book/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
